name: Release and Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  version-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - name: Create version bumps and changelogs with Changesets
        run: bunx changeset version
      - name: Commit and push changelogs and versions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): version bump & changelog [skip ci]" || echo "No changes to commit"
          git push

  publish:
    needs: version-and-changelog
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - name: Publish packages with Changesets
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bunx changeset publish
